# See `@heroiclands/package-build` for the full documentation.
#

contentPackage: harnensemble
packageKind: modules

stats:
    lastModifiedBy: harnensbuild0000

compatibility:
    minimum: "14.359"
    verified: "14.367"

packs:
    - name: actors-hm3
      label: Actors
      type: Actor
      system: hm3
    - name: actors-sohl
      label: Actors
      type: Actor
      system: sohl
    - name: journals
      label: Journals
      type: JournalEntry

publish:
    site: false
    manifests: { publish: false, consume: false }

packageBuild:
    assets:
        - { from: assets/images, to: assets/images }
        - { from: LICENSE, to: LICENSE }
        - { from: README.md, to: README.md }

    manifest:
        title: Ensemble of Hârn NPCs
        description: >-
            Over a thousand ready-made NPCs for you to use
            in your games in the Hârn setting.
        authors:
            - name: Toasty
              discord: toasty#8538
              flags: {}
        license: LICENSE
        readme: README.md
        packFolders:
            - name: Hârn Ensemble
              sorting: m
              color: "#5b2c1d"
              packs:
                  - actors-hm3
                  - actors-sohl
                  - journals
        flags:
            allowBugReporter: true
